package GUI;

import DLL.DepartmentDLL;
import DLL.EmployeesDLL;
import DLL.ProjectDLL;
import Entity.Department;
import Entity.Employees;
import Entity.Project;
import java.awt.GraphicsConfiguration;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOAN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    EmployeesDLL empDLL = new EmployeesDLL();
    DepartmentDLL depDLL = new DepartmentDLL();
    ProjectDLL prDLL = new ProjectDLL();
    
    ArrayList<Employees> listEMP = new ArrayList<>();
    ArrayList<Department> listDep = new ArrayList<>();
    ArrayList<Project> listPr =  new ArrayList<>();

    public Main(GraphicsConfiguration gc) {
        super(gc);
    }
    
    public Main() {
        initComponents();
        Binding();
        BindingDep();
        BindingProject();   
    }
    
    public void Binding(){
        listEMP = empDLL.getAll();
        Vector clm = new Vector();
        clm.add("User");
        clm.add("Pass");
        clm.add("Họ tên");
        clm.add("Age");
        clm.add("Địa chỉ");
        clm.add("Phone");
        clm.add("Phòng ban");
        clm.add("Dự án");
        
        Vector data = new Vector();
        for (Employees emp : listEMP) {
            Vector row = new Vector();
            row.add(emp.getUsername());
            row.add(emp.getPassword());
            row.add(emp.getFullName());
            row.add(emp.getAge());
            row.add(emp.getAddress());
            row.add(emp.getPhone());
            
            listDep = depDLL.getByID(emp.getDepID());
            if (listDep.size() > 0) {
                row.add(listDep.get(0).getDepName());
            }else{
                row.add("-");
            }
            listPr = prDLL.getByID(emp.getPrID());
            if (listPr.size() > 0) {
                row.add(listPr.get(0).getPrName());
            }else{
                row.add("-");
            }
            
            data.add(row);
        }
        
        DefaultTableModel dtm = new DefaultTableModel(data, clm);
        tblEmp.setModel(dtm);
        
        tblEmp.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblEmp.getColumnModel().getColumn(1).setPreferredWidth(35);
        tblEmp.getColumnModel().getColumn(2).setPreferredWidth(120);
        tblEmp.getColumnModel().getColumn(3).setPreferredWidth(10);
        tblEmp.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblEmp.getColumnModel().getColumn(5).setPreferredWidth(60);
        tblEmp.getColumnModel().getColumn(6).setPreferredWidth(130);
        tblEmp.getColumnModel().getColumn(7).setPreferredWidth(100);
    }
    
    public void BindingDep(){
        listDep = depDLL.getAll();
        for (Department d : listDep) {
            cboDep.addItem(d.getDepName());
        }
    }
    
    public void BindingProject(){
        listPr = prDLL.getAll();
        for (Project p : listPr) {
            cboProject.addItem(p.getPrName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmp = new javax.swing.JTable();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtFullname = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        cboDep = new javax.swing.JComboBox();
        cboProject = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblWellcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý dự án");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Xin chào: ");

        tblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmp);

        jLabel2.setText("User:");

        jLabel3.setText("Password:");

        jLabel4.setText("Full name:");

        jLabel5.setText("Age:");

        jLabel6.setText("Address:");

        jLabel7.setText("Phone:");

        jLabel8.setText("Department:");

        jLabel9.setText("Project:");

        btnAdd.setText("Add new");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblWellcome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWellcome.setForeground(new java.awt.Color(255, 0, 51));
        lblWellcome.setText("jindo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblWellcome))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtFullname, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(20, 20, 20))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(9, 9, 9)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txtPhone))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(23, 23, 23)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboProject, 0, 155, Short.MAX_VALUE)
                                            .addComponent(cboDep, 0, 155, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete)))))
                        .addGap(75, 75, 75)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblWellcome))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        listDep = depDLL.getAll();
        listPr = prDLL.getAll();
        
        String User = txtUser.getText();
        String pass = txtPass.getText();
        String FName = txtFullname.getText();
        String Age = txtAge.getText();
        String Address = txtAddress.getText();
        String Phone = txtPhone.getText();
        
        int rowDep = cboDep.getSelectedIndex();
        int rowPr = cboProject.getSelectedIndex();
        
        int idDep = listDep.get(rowDep).getDepID();
        int idPr = listPr.get(rowPr).getPrID();
        
        Employees emp = new Employees();
        emp.setUsername(User);
        emp.setPassword(pass);
        emp.setFullName(FName);
        emp.setAge(Age);
        emp.setAddress(Address);
        emp.setPhone(Phone);
        emp.setDepID(idDep);
        emp.setPrID(idPr);
        
        if (empDLL.AddData(emp)) {
            JOptionPane.showMessageDialog(this, "Add new emp success.");
            clearText();
            Binding();
        }else{
            JOptionPane.showMessageDialog(this, "Add new emp fail.");
            clearText();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    public void clearText(){
        txtFullname.setText(null);
        txtUser.setText(null);
        txtAddress.setText(null);
        txtAge.setText(null);
        txtPass.setText(null);
        txtPhone.setText(null);
        cboDep.setSelectedIndex(0);
        cboProject.setSelectedIndex(0);
   }
    
    private void tblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpMouseClicked
        int row = tblEmp.getSelectedRow();
        //listDep = depDLL.getAll();
        //listPr = prDLL.getAll();
        listEMP = empDLL.getAll();
        
        txtUser.setText(listEMP.get(row).getUsername());
        txtPass.setText(listEMP.get(row).getPassword());
        txtFullname.setText(listEMP.get(row).getFullName());
        txtAge.setText(listEMP.get(row).getAge());
        txtAddress.setText(listEMP.get(row).getAddress());
        txtPhone.setText(listEMP.get(row).getPhone());
        
        listDep = depDLL.getByID(listEMP.get(row).getDepID());
        cboDep.setSelectedItem(listDep.get(0).getDepName());
        
        listPr = prDLL.getByID(listEMP.get(row).getPrID());
        if (listPr.size() > 0) {
            cboProject.setSelectedItem(listPr.get(0).getPrName());
        }else{
            cboProject.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_tblEmpMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        listDep = depDLL.getAll();
        listPr = prDLL.getAll();
        listEMP = empDLL.getAll();
        
        String User = txtUser.getText();
        String pass = txtPass.getText();
        String FName = txtFullname.getText();
        String Age = txtAge.getText();
        String Address = txtAddress.getText();
        String Phone = txtPhone.getText();
        
        int rowDep = cboDep.getSelectedIndex();
        int rowPr = cboProject.getSelectedIndex();
        int row = tblEmp.getSelectedRow();
        
        int idDep = listDep.get(rowDep).getDepID();
        int idPr = listPr.get(rowPr).getPrID();
        
        Employees emp = new Employees();
        emp.setUsername(listEMP.get(row).getUsername());
        emp.setPassword(pass);
        emp.setFullName(FName);
        emp.setAge(Age);
        emp.setAddress(Address);
        emp.setPhone(Phone);
        emp.setDepID(idDep);
        emp.setPrID(idPr);
        
        if (empDLL.update(emp)) {
            JOptionPane.showMessageDialog(rootPane, "Update success");
            Binding();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Update fail");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (tblEmp.getSelectedRow() != -1) {
            int row = tblEmp.getSelectedRow();
            listEMP = empDLL.getAll();
            
            if (empDLL.delete(listEMP.get(row).getUsername())) {
                JOptionPane.showMessageDialog(rootPane, "Delete emp success");
                Binding();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Delete fail");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cboDep;
    private javax.swing.JComboBox cboProject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    protected static javax.swing.JLabel lblWellcome;
    private javax.swing.JTable tblEmp;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
